# For more info on HTTP files go to https://aka.ms/vs/httpfile
@root = https://localhost
@port = 7166
@contentType = application/json
@acceptLanguae = en-US,en;q=0.5

# Register
POST {{root}}:{{port}}/auth/register
Content-Type: {{contentType}}
Accept-Language: {{acceptLanguae}}

{
        "firstName": "Nawar",
        "lastName": "Ali",
        "email": "nr.ali1912@gmail.com",
        "password": "password"
}